### ISSUE TITLE
May I use this?

### ISSUE THREAD

**Issue by mikolertesx** [Arthur944/remembering-the-kanji-stories#2]
I wanted to make a deck, and make it public in kitsun.io.
And I wanted to know if you wouldn't mind, since you basically made all the work of recopiling it.
![imagen](https://user-images.githubusercontent.com/13491373/166340788-af1eb688-f238-4ebe-86f9-69427d552b21.png)

**Comment by Arthur944** [comment]
Hi, sure go ahead I'm glad you found a use for it :)
